ska-sa/katsdpimager

doc/user.rst

It is updated for
- move to katsdpimager top-level repo
- open-sourcing
- imager-dev branch being retired
- pybind11 branch no longer being needed
- new versions of misc dependencies

Update installation documentation

---

katsdpimager/optional.h
requirements.txt

Due to an older pybind11 bug, I was using a modified copy of it's
optional_caster template, and it was out of sync with changes in more
recent versions of pybind11. Removing the workaround fixed things.

Fix compilation against pybind11 >= 2.3

---

.gitignore
LICENSE
katsdpimager/preprocess.cpp
manylinux/Dockerfile
manylinux/generate_wheels.sh
mkwheels.sh
pyproject.toml
setup.py

Additionally, some safety checks are added to setup.py to warn about
common errors, and pybind11 is removed from pyproject.toml (it was
accidentally added when creating pyproject.toml).

Add tools for building binary wheels

---

katsdpimager/frontend.py
katsdpimager/preprocess.cpp

Zero-weight data is eliminated during preprocessing, and channels with
no visibilities left are skipped early.
Closes SPR1-233.

Faster handling of all-flagged channels

---

manylinux/generate_wheels.sh

The previous change broke the generate_wheels script. We're depending on
PEP 517 build isolation, but that required `pip wheel` not `setup.py
bdist_wheel`.

Fix generation of binary wheels

---

.dockerignore
manylinux/generate_wheels.sh
setup.py

Hopefully *this* PR will now make things ready for release. The wheel building process ended up dirtying the source tree, which made katversion use a dirty version number instead of the shiny tag.

Katversion tweaks

---

katsdpimager/preprocess.cpp
katsdpimager/test/test_preprocess.py

Zero weights generally indicates flagging, and if any
polarisation if flagged then at least one of the inputs is
contaminated and so no Stokes parameters will be clean.
The unit test needed changing because one of the test visibilities had
a single zero weight. I changed that weight, and added a new visibility
that I expect to be skipped.
I cheated on the new expected values in the test: I updated them to
match the actual values coming out after I changed the zero weight.
See SPR1-374.

Discard visibilities with zero weight on any polarisation.

---

katsdpimager/imaging.py

The PSF and dirty image are switched at some point, so they need to have
compatible padding requirements, which happened by change for many image
sizes but not all. This is now explicitly enforced.
Closes SPR1-420.

Fix crash that occurs with some image sizes

---

katsdpimager/loader_katdal.py

This can significantly reduce memory usage (by over 1GB in some cases).
I suspect it will also slightly improve performance although I haven't
measured it.

katdal loader: select only relevant channels

---

scripts/imager-mkat-pipeline.py

For unknown reasons there was garbage accumulating that held on to GPU
memory and it wasn't automatically being collected.
Fixes SPR1-474.

Do a full garbage collect after writing results

---

scripts/imager-mkat-pipeline.py
scripts/imager.py

It is supposed to be "Jy/beam" in FITS. The core io function had been
fixed, but it was being overridden by the scripts.

Fix more instances of JY/BEAM (all caps)

---

katsdpimager/test/test_sky_model.py

The mocking of redis to substitute fakeredis was broken by changes in
katsdptelstate.

Fix unit tests

---

katsdpimager/frontend.py
katsdpimager/loader_core.py
katsdpimager/loader_katdal.py
katsdpimager/report.py
katsdpimager/templates/report.html.j2
katsdpimager/test/test_weight.py
katsdpimager/weight.py
scripts/imager-mkat-pipeline.py

Add an extra line to the imaging report plot that predicts noise from the visibility weights. I wasn't quite sure how to label this to avoid confusion with the other prediction, but eventually ended up with "Predicted noise (weights)" and "Predicted weights (model)".
Closes SPR1-528.

Predict noise from weights

---

katsdpimager/report.py
katsdpimager/templates/report.html.j2
setup.py

It's added as an embedded SVG generated by matplotlib, rather than a
Bokeh plot, because Bokeh doesn't currently support elliptic arcs
(although matplotlib fakes them with Bezier curves, so it's possible
that this could be ported to Bokeh).
There may be some numerical stability issues for targets *exactly* on
the equatorial plane of date, because in that case the ellipse degrades
to a line. Targets with DEC=0 should generally be okay though because
that's the J2000 equator, which is not the same thing.

Plot UV coverage in the report

---

.gitmodules
pyproject.toml
setup.py

Update pybind11 to 2.5.0 and load it via pyproject.toml rather than a
git submodule (2.5.0 finally plays nice with build isolation).

Unvendor pybind11

---

katsdpimager/arguments.py
katsdpimager/frontend.py
katsdpimager/io.py
katsdpimager/loader_core.py
katsdpimager/loader_katdal.py
katsdpimager/loader_ms.py
katsdpimager/polarization.py
katsdpimager/test/test_arguments.py
scripts/imager-mkat-pipeline.py
scripts/imager.py

This is made much more complicated by the need to remove
authentication-related information, which precludes just dumping
`sys.argv`. So instead functions are added to reconstruct an equivalent
command line from the parsed args.
Closes SPR1-498.

Add command-line arguments as HISTORY to the FITS file

---

Jenkinsfile
doc/user.rst
katsdpimager/frontend.py
katsdpimager/loader_core.py
katsdpimager/loader_katdal.py
requirements.txt
setup.py

When `-i rfi-mask=fixed` or `-i rfi-mask=config` is given, use the appropriate RFI mask for the telescope state.
It's not the most optimised implementation in terms of skipping work as early as possible. It's really aimed at the automated pipeline, which will itself skip launching imaging tasks if they contain no work.

Add option to use RFI mask

---

katsdpimager/profiling.py

If an exception is thrown into a generator wrapped with
`@profile_generator` (in particular, if the generator is closed before
it finishes naturally), then the stopwatch will have been stopped inside
the context manager, and the context manager cleanup would try to stop
it again, raising an exception.
Instead, silently do nothing on a double stop.

Don't raise an exception if a Stopwatch is stopped twice

---

doc/user.rst
katsdpimager/loader_katdal.py

This makes little difference to performance at the moment, but makes the
channel status in the report more representative.

Apply band mask in addition to RFI mask to skip channels

---

katsdpimager/loader_katdal.py

This gives better RFI/band masking by masking channels that are only
partially masked.

Pass channel width to katsdpmodels

---

katsdpimager/profiling.py
katsdpimager/test/test_profiling.py

When the generator yielded, the timer was stopped, but it would still
appear in the stack trace if other profiled functions were called while
the generator was alive. I think this could severely mess up flamegraphs
because time spent in children is subtracted from total time to get time
spent only in self.
To fix this, pushing and popping the frame is now handled by the
stopwatch class on each stop and start.

Fix stack traces when using profile_generator

---

katsdpimager/preprocess.py

It turns out that reading and writing the temp file is CPU-bound rather
than I/O-bound (when run on imgr6, which has only one NVMe; on other
imaging machines with two in RAID-0, it will be even worse). Turning off
decompression on one test made the file about 20% bigger but reduced the
time for the whole imaging process by 35%.

Do not use gzip compression in HDF5 temp file

---

katsdpimager/io.py

Using np.nanmin took a slow path in numpy, where it replaces all the
NaNs with +inf, computes the min, then restores the NaNs.

Speed up computation of DATAMIN and DATAMAX in write_fits_image

---

katsdpimager/clean.py
katsdpimager/frontend.py
katsdpimager/grid.py
katsdpimager/image.py
katsdpimager/imaging.py
katsdpimager/io.py
katsdpimager/parameters.py
katsdpimager/predict.py
katsdpimager/preprocess.py
katsdpimager/test/test_clean.py
katsdpimager/test/test_grid.py
katsdpimager/test/test_predict.py
katsdpimager/test/test_preprocess.py
scripts/imager-mkat-pipeline.py

Avoid recompiling the CUDA kernels and related infrastructure for every channel. This reduces runtime by around 15% (in one test - probably less for longer observations since the cost is amortised).
It's a big diff for a fairly small functional change, which is due to refactoring to split out channel-independent pieces:
- New `FixedImageParameters` and `FixedGridParameters` classes hold only channel-independent information, and are referenced by the full `ImageParameters` and `GridParameters`.
- The convolution kernel is moved from `GridderTemplate` (and `DegridderTemplate`) to `GridDegrid`, so that the former can be channel-independent.
- The `psf_patch` and `border` fields in `CleanParameters` are now fractions of the image size (as specified on the command line) and converted to pixel …

Reuse sigproc templates

---

katsdpimager/preprocess.py

PR #70 removed gzip compression from the temporary HDF5 file, but the
code that printed the gzip compression ratio lingered. Remove it too.

Don't print file compression ratio

---

katsdpimager/frontend.py
katsdpimager/loader_core.py
katsdpimager/loader_katdal.py
katsdpimager/loader_ms.py
katsdpimager/preprocess.cpp
katsdpimager/preprocess.py
katsdpimager/test/test_preprocess.py

Previously, the preprocessing would sort by (channel, w_slice, baseline). Visibilities in a batch are already processed in channel-major order, so we can skip sorting by channel. We can also switch the sort order to (baseline, w_slice) with very little loss in compression efficiency; that allows sorting by baseline to be made the caller's problem, which is easy for katdal (just a transpose) and still quite cheap for an MS (requires an argsort but it is channel-independent). Finally, sorting by w_slice can be done in linear time with a bucket-sort, because we expect only a small number (dozens) of w slices.
The preprocessor had a feature where a baseline index could be set to a negative value to indicate an autocorrelation to skip, but it wasn't actually used (both loaders did their own …

Change sorting approach for preprocessing

---

simulation-requirements.txt

There is a security advisory on the previous version. It's probably
harmless since it's only required by nbconvert, which I don't expect to
be run as part of simulations, but this will keep Dependabot happy.

Bump bleach to latest version

---

katsdpimager/frontend.py
katsdpimager/preprocess.cpp

The preprocessing is offloaded to a separate thread, which drops the GIL
to allow parallel work. It ends up only making a small difference,
because the loading is slowed down (not sure if that's contention for
the GIL or for memory).

Do data loading in parallel with preprocessing 

---

katsdpimager/preprocess.cpp
setup.py

For a test with katdal, this made preprocessing effectively free as it
overlapped entirely with data loading. It does, however, slow down the
data loading, presumably due to memory contention (it did not seem to
saturate the CPU cores).

Use OpenMP to accelerate preprocessing

---

katsdpimager/loader_katdal.py
katsdpimager/test/test_arguments.py
katsdpimager/test/test_loader_katdal.py
katsdpimager/test/test_profiling.py
katsdpimager/test/test_sky_model.py

This is mainly to cover `data_iter`, given that it has recently been optimised. There are still some gaps in test coverage (particularly `_find_target`).
This did turn up one bug, namely that uvw were being returned as numpy arrays rather than as distance Quantities.

Unit tests for LoaderKatdal

---

doc/user.rst
katsdpimager/loader_katdal.py
katsdpimager/test/test_loader_katdal.py

They wouldn't have worked anyway after #79, but more importantly, it
would never have been useful because no calibration would have been
applied.
This allows some simplification, because several code paths had to have
fallbacks for when v4 features are not available. Also remove the spw
and subarray command-line arguments since v4 only supports one of each.

Remove support for .h5 katdal datasets

---

katsdpimager/frontend.py
setup.py

numpy 1.17 provides a `where` option to np.sum which allows nansum to be
computed faster.

Speed up computation of total flux

---

katsdpimager/predict.py
katsdpimager/sky_model.py

They were somehow slow, and only depend on phase centre (not frequency).
Slap a functools.lru_cache on it, and return a read-only array to
prevent accidental modification of the cached value.

Cache results of lmn calculations

---

katsdpimager/grid.py

While vectorisation may have some intrinsic benefits, the main advantage
is that the (expensive) kaiser_bessel_fourier call is independent of w
and hence gets called an order of magnitude less.
In my test this shaves off about 5% of total runtime.

Vectorise antialias_w_kernel

---

katsdpimager/clean.py
katsdpimager/imaging.py
katsdpimager/predict.py
katsdpimager/test/test_predict.py

Store a `set` of pixels that have been set in the model image, instead
of searching for them on each major cycle. This should speed things up a
little.

Track CLEAN components

---

katsdpimager/frontend.py
katsdpimager/image.py
katsdpimager/imager_kernels/apply_primary_beam.mako
katsdpimager/imaging.py
katsdpimager/test/test_image.py

This should improve performance, and avoids moving the dirty image to
the CPU for correction then back to the GPU for convolution with the
restoring beam.
A side effect is that if the primary beam is written to file it will not
be clipped (as the clipping now happens on application).

Apply primary beam correction on the GPU

---

katsdpimager/beam.py
katsdpimager/fft.py
katsdpimager/frontend.py
katsdpimager/image.py
katsdpimager/imaging.py
katsdpimager/test/test_beam.py
katsdpimager/test/test_fft.py

- Move command_queue from template to operation.
- Explicitly expose the work area as a slot.
- Lock the template when enqueuing the operation. It's now safe to have
multiple operations made from the same template and call them
concurrently (previously even doing it serially was unsafe due to
clobbering the single work area).
- Check the version of CUFFT before enabling the workaround for CUFFT
7.0, so that it will not slow down more modern versions.

Some rework on FFT

---

katsdpimager/fft.py
katsdpimager/test/test_fft.py

This was never actually used (as far as I know), but was added at the
time because it seemed trivial to support. However, it was failing after
updating some code. CUFFT does joint processing on several batches and then disentangles
them. When some of those batches contain uninitialised padding data,
this can lead to problem if the uninitialised data is very large
compared to the real data (or even Inf/NaN).

Remove ability to pad FFTs along batch dimensions

---

doc/macros.rst
katsdpimager/beam.py
katsdpimager/clean.py
katsdpimager/fft.py
katsdpimager/grid.py
katsdpimager/image.py
katsdpimager/predict.py
katsdpimager/weight.py

This makes the docstrings shorter, and also removes references to
SVMAllocator which may no longer be appropriate.

Update docstring types to use katsdpsigproc.abc abstract types

---

katsdpimager/clean.py

A value read asynchronously was being used before blocking on the
transfer completing. It isn't currently a bug because with unified
memory/SVM, get_async isn't actually async, but it will become a bug
once I strip out unified memory.

Fix a bug-in-waiting in clean

---

katsdpimager/clean.py
katsdpimager/imaging.py
katsdpimager/predict.py
katsdpimager/test/test_predict.py

This removes the need for the CPU to read from the model image.
Eventually the model image (as an image) could be dispensed with
entirely when not doing degridding, and reconstituted only right at the
end.

Track full model on CPU as a dictionary of CLEAN components

---

katsdpimager/profiling.py
scripts/imager-mkat-pipeline.py

It uses excessive memory. This is a quick fix for SPR1-919, but a proper
fix would be to accumulate flamegraph data on the fly.

Disable profile collection for imager-mkat-pipeline.py 

---

katsdpimager/profiling.py
katsdpimager/test/test_profiling.py
scripts/imager-mkat-pipeline.py
scripts/imager.py

This reenables profile collection without the issues caused in
SPR1-919.
- The default Profiler is now changed to NullProfiler, so that only code
that explicitly opts in to profiling will get it.
- Profiler is now an abstract base class, with record handling
implemented add_record / add_device_record provided by the subclass.
- The original functionality has been split into two classes:
1. CollectProfiler collects complete records. It's used for unit
testing.
2. FlamegraphProfiler aggregates statistics as they're received, to
keep memory usage bounded independent of the number of channels
processed. To avoid blocking on the device, DeviceRecords are put
in a queue for aging so that by the time we want to know the
runtime the work should generally have completed. The queue size
is bounded …

Rewrite of profiling collection and reporting

---

tests/simulate.py

katpoint (1.0 dev version) now supports directly creating a Target from
a SkyCoord, and the previous way I was creating a Target no longer
works.
Closes SPR1-920.

Update katpoint usage in simulate.py for upstream changes

---

tests/images_report.py

It keeps running out of memory when run under Jenkins because it assumes
it can use all the memory in the system.

Limit wsclean memory usage

---

simulation-requirements.txt

Just to keep dependabot happy - there shouldn't be any actual security
impact since it is just used to generate simulation data.

Update pillow to the latest version

---

katsdpimager/frontend.py
katsdpimager/parameters.py
katsdpimager/primary_beam.py
katsdpimager/test/test_primary_beam.py

This module pre-dated katsdpmodels.primary_beam and tried to present a
very general interface, but a different one to katsdpmodels. In future
katsdpmodels will be used for the primary beam models, and the
TrivialPrimaryBeam will be for backwards compatibility. It's thus
convenient for it to implement the common PrimaryBeam interface.
In theory it would now be possible to support any circularly-symmetric
PrimaryBeam, but since TrivialPrimaryBeam is the only such interface,
there is no point trying to accept arbitrary PrimaryBeam models until
there is support for models that rotate over time.
See SPR1-855.

Rewrite primary_beam module in terms of katsdpmodels.primary_beam

---

Jenkinsfile.report

Send it to the mail alias used by the main Jenkinsfile instead.

Stop sending test image report to bmerry
