ska-sa/katsdpimager

- .flake8
- .gitignore
- .gitmodules
- MANIFEST.in
- pyproject.toml
- requirements.txt
- setup.py
Due to https://github.com/pybind/pybind11/issues/1067 it doesn't work to
use setup_requires or pyproject.toml to automatically install it at
build time.
Added a pyproject.toml to ensure that pkgconfig is installed.
> Vendor in pybind11

- Dockerfile
- Jenkinsfile
- README.rst
- doc/changelog.rst
- doc/index.rst
- doc/modules.rst
- doc/user.rst
- katsdpimager/__init__.py
- pyproject.toml
- setup.py
- Use katversion
- Update email address (@sratcliffe: alias required)
- Add Trove classifiers
- Update installation instructions
- Add a changelog
> More preparations for PyPI release

- report-requirements.txt
Github complains about a CVE on the prior version.
> Bump pillow to the latest version

- katsdpimager/imager_kernels/predict.mako
The arrays are not padded to deal with the rounding in the number of
threads. That might be a better solution, but that would require some
refactoring. The changes to prevent out-of-bounds accesses are outside
the critical loops so it shouldn't affect performance much.
This fixes the crash in SPR1-298, but there is still another (unrelated)
test failure.
> Fix out-of-bounds memory accesses in predict kernel

- katsdpimager/loader_ms.py
It was measuring north as the angle of the great circle (in AltAz frame)
towards the celestial north pole. However, converting FK5 -> AltAz does
not preserve great circles.
Replace the pole with a point infinitesimally north of the target.
Closes SPR1-140 / SPAZA-24.
> Correct calculation of parallactic angles

- katsdpimager/loader_katdal.py
- Load vis, weights and flags together (closes SPR1-359)
- Align loads to chunk boundaries, to avoid loading some chunks twice.
> Access data from katdal more efficiently

- katsdpimager/io.py
- katsdpimager/loader.py
- katsdpimager/loader_core.py
- katsdpimager/loader_katdal.py
- katsdpimager/loader_ms.py
- manylinux/generate_wheels.sh
- setup.py
Adds extra FITS headers to the output. Some are specifically to allow calculation of radial velocities, while others are just extra provenance information.
I've tried to avoid adding too much information that can be retrieved from the original katdal dataset, instead listing the information necessary to obtain it.
> More FITS headers

- doc/changelog.rst
- doc/user.rst
Just documentation of what's been added.
> Prepare for a 1.2 release

- doc-requirements.txt
- report-requirements.txt
- requirements.txt
- test-requirements.txt
This should be merged together with ska-sa/katsdpdockerbase#46. It may
currently fail to build until that branch is merged.
> Update requirements to match katsdpdockerbase update

- katsdpimager/frontend.py
- katsdpimager/io.py
Somehow I missed these in #33.
> Yet more places using all-caps JY

- setup.py
- test-requirements.txt
It's now needed to use fakeredis with katsdptelstate.
> Add lupa to test-requirements

- katsdpimager/clean.py
- katsdpimager/frontend.py
- katsdpimager/imager_kernels/clean/rank.mako
- katsdpimager/imaging.py
- katsdpimager/loader_katdal.py
- katsdpimager/report.py
- katsdpimager/test/test_clean.py
- setup.py
Some of the bugs are in the report, some are in the imager itself but were exposed by the report. The commits are largely independent so refer to each commit for explanations.
@ludwigschwardt would you mind looking at this, since the meaty parts involve stats?
> Fix assorted bugs seen in imaging report

- katsdpimager/report.py
- katsdpimager/templates/report.html.j2
Also expanded on the explanation of the SEFD model in the report.
> Add UHF SEFD model

- katsdpimager/frontend.py
- scripts/imager-mkat-pipeline.py
> Defer writing statistics to telstate until end

- requirements.txt
katsdpdockerbase has updated to defaults that are at least as new.
> Unpin some requirements in requirements.txt

- katsdpimager/frontend.py
- scripts/imager-mkat-pipeline.py
If the pipelining imaging dies and is retried, detect channels that were
successfully imaged and skip them next time.
Also put in some defense against the case where the statistics are
written but the imager dies before reaching the checkpoint. This should
be less common now that the checkpoint" is a telstate key alongside the
other telstate keys (rather than successful process termination, which
can go wrong if Docker is having a bad hair day).
Closes SPR1-622.
> Checkpoint pipeline imaging state

- katsdpimager/frontend.py
- katsdpimager/progress.py
- requirements.txt
- setup.py
It makes progress bars implement the context manager protocol, so I was
able to built my jury-rigged one. It also looks like it's a bit more
robust about restoring the terminal cursor if the process dies (using an
atexit handler).
> Update to latest version of progress package

- katsdpimager/sky_model.py
> Workaround for incorrect stream types

- scripts/imager-mkat-pipeline.py
It was taking about 1/3 of the total runtime.
> Skip writing the large PNG visualisation

- katsdpimager/frontend.py
- scripts/imager-mkat-pipeline.py
These will all be useful for doing comparisons to the parametric model.
> Collect more statistics from the imager

- scripts/imager-mkat-pipeline.py
Every imaging run tries to put its flamegraph results into the same
telstate immutable key. Use an indexed key instead, and use the helper
function that deals gracefully with the sub-key already being there.
> Fix crash at end of imager-mkat-pipeline.py

- katsdpimager/frontend.py
- katsdpimager/imaging.py
- katsdpimager/preprocess.py
- scripts/imager-mkat-pipeline.py
This data will help with producing a report on the imager performance.
> More profiling and stats data

- katsdpimager/frontend.py
It was broken by recent merges.
> Fix for --host mode

- katsdpimager/loader_katdal.py
This significantly accelerates the loading, to the point where
preprocessing becomes the limiting factor again.
It's untested for pre-v4 MVF, but I plan to drop support for that anyway.
> Do more katdal loading via dask

- katsdpimager/frontend.py
- scripts/imager-mkat-pipeline.py
- scripts/imager.py
They're not used yet, but will be used in future to avoid retrieving
data from the GPU if it is not required.
> Add needs_fits_image and needs_fits_grid to Writer API

- katsdpimager/io.py
- scripts/imager-mkat-pipeline.py
This roughly halves the time taken to write the thumbnail. The resulting
image does look fairly different, because the noise is smoothed out and
this causes the colour scale to be tighter. That has the effect of
making the real flux stand out a bit better, so I'm happy with it.
> Downsample image before writing the thumbnail

- katsdpimager/frontend.py
- katsdpimager/imaging.py
- katsdpimager/preprocess.py
> Optimise transfer of UV coordinates

- requirements.txt
Now that ska-sa/katsdpdockerbase#61 has been merged.
> Unpin bokeh and jinja2

- simulation-requirements.in
- simulation-requirements.txt
- tests/simulate.py
It contains one bug fix that allows a workaround to be removed from the script.
> Upgrade simulation from rascil 0.2.0b0 to 0.2.0

- simulation-requirements.txt
The old version has a security issue which was upsetting dependabot.
> Bump version of lxml used in simulation

- tests/simulate.py
This needed a bit of adaptation to pass the values to RASCIL.
> katpoint.Target.uvw is now CartesianRepresentation

- test-requirements.txt
This is precipitated by fakeredis 2.10.0 in docker base.
> SPR1-2766: Update lupa to docker base version

- test-requirements.txt
Not entirely sure why it wasn't there before.
> Add pytest to test-requirements.txt
